import type { Metadata } from "next"
import { Figtree, Oswald, Shadows_Into_Light } from "next/font/google"
import "./globals.css"

// Body text: forms, paragraphs, prices, buttons
const figtree = Figtree({
  variable: "--font-figtree",
  subsets: ["latin"],
})

// Big titles: free stand-in for Balboa
const oswald = Oswald({
  variable: "--font-oswald",
  subsets: ["latin"],
})

// Handwritten accents: notes, doodles, easter eggs (only has weight 400)
const shadowsIntoLight = Shadows_Into_Light({
  variable: "--font-shadows-into-light",
  subsets: ["latin"],
  weight: "400",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${figtree.variable} ${oswald.variable} ${shadowsIntoLight.variable} h-full antialiased`}
    >
      <body className="flex min-h-full flex-col">{children}</body>
    </html>
  )
}
